### ISSUE TITLE
Moving Project  to Kyverno Org

### ISSUE THREAD

**Issue by fjogeleit** [VELUX/backstage-policy-reporter-plugin#2]
Hey @Jonas-Beck @Jaxwood,

happy to share that we started with the GitVote https://github.com/kyverno/community/pull/30 to move this project to the [Kyverno Org](https://github.com/kyverno).

For this we need to clarify a view things:

* Who will be the Maintainer of this Project? Will @Jonas-Beck and @Jaxwood continue as Maintainers?
* Do you have a rough roadmap for the project? 
  * Like handling different engines/sources of Policy Reports
  * Policy Reporter v3 will be GA soon, we should check that it also works with the new version but can also check if new APIs could help to improve the UI/UX.

**Comment by Jonas-Beck** [comment]
Hey @fjogeleit,

Sounds great with the GitVote! We would like to continue maintaining this project going forward.

Here are some of our ideas we would like to explore in the future:

- Add support for Basic Auth when requesting policies from the cluster.
- Add support for Policy Reporter v3 when it's GA.
- Add support for handling different engines/sources of Policy Reports.

Aside from this, we will, of course, keep it updated with the latest Backstage updates.
